# Specify the version of the Docker Compose.
version: "3.9"

services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      # volumes:
      #   - ./frontend:/app
      ports:
        - "3000:3000"

  api-gateway:
    build: 
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    # volumes:
    #   - ./backend/api-gateway:/app

  question-app:
    build: 
      context: ./backend/question-service
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8001
    # volumes:
    #   - ./backend/question-service:/app

  user-app:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile.dev
    ports:
      - 8003:8003
    # volumes:
    #   - ./backend/user-service:/app
    depends_on:
      - user-service-db

  user-service-db:
    container_name: user-service-db
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet --logpath /dev/null
