# Specify the version of the Docker Compose.
version: "3.9"

services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      # volumes:
      #   - ./frontend:/app
      ports:
        - "3000:3000"

  api-gateway:
    build: 
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    environment:
      QUESTION_SERVICE_DOMAIN: ${QUESTION_SERVICE_DOMAIN}
      USER_SERVICE_DOMAIN: ${USER_SERVICE_DOMAIN}
    ports:
      - 8000:8000
    # volumes:
    #   - ./backend/api-gateway:/app

  question-app:
    build: 
      context: ./backend/question-service
      dockerfile: Dockerfile.dev
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_NAME: ${MONGODB_NAME}
    ports:
      - 8001:8001
    # volumes:
    #   - ./backend/question-service:/app

  matching-app:
    build: 
      context: ./backend/matching-service
      dockerfile: Dockerfile.dev
    environment:
      KAFKA_BROKER_URI: ${KAFKA_BROKER_URI}
      MATCHING_SERVICE_CONSUMER_GROUP_ID: ${MATCHING_SERVICE_CONSUMER_GROUP_ID}
    depends_on:
      - kafka
    ports:
      - 8002:8002
    # volumes:
    #   - ./backend/matching-service:/app

  matching-websocket:
    build:
      context: ./backend/matching-websocket-service
      dockerfile: Dockerfile.dev
    environment:
      KAFKA_BROKER_URI: ${KAFKA_BROKER_URI}
      MATCHING_WEBSOCKET_SERVICE_CONSUMER_GROUP_ID: ${MATCHING_WEBSOCKET_SERVICE_CONSUMER_GROUP_ID}
      COLLAB_SERVICE_DOMAIN: ${COLLAB_SERVICE_DOMAIN}
    depends_on:
      - kafka
    ports:
      - 8008:8008
    # volumes:
    #   - ./backend/matching-websocket-service:/app

  collab-app:
    build: 
      context: ./backend/collab-service
      dockerfile: Dockerfile.dev
    environment:
      QUESTION_SERVICE_DOMAIN: ${QUESTION_SERVICE_DOMAIN}
    depends_on:
      - question-app
    ports:
      - 8007:8007
    # volumes:
    #   - ./backend/collab-service:/app

  user-app:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile.dev
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_CLOUD_URI: ${DB_CLOUD_URI}
      DB_LOCAL_URI: ${DB_LOCAL_URI}
      PORT: ${PORT}
      ENV: ${ENV}
    ports:
      - 8003:8003
    # volumes:
    #   - ./backend/user-service:/app
    depends_on:
      - user-service-db

  user-service-db:
    container_name: user-service-db
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet --logpath /dev/null

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 8004
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:8004
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:8005,PLAINTEXT_HOST://localhost:28005
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8006:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./backend/kui/config.yaml:/etc/kafkaui/dynamic_config.yaml

  redis:
    container_name: matching-redis
    image: redis:latest
    # No need to expose the port as it is only used internally (6379)