# Specify the version of the Docker Compose.
version: "3.9"

services:
  user-app:
    build: 
      context: ./user-service
      dockerfile: Dockerfile.dev
    ports:
      - 8003:8003
    volumes:
      - ./user-service:/app
    depends_on:
      - user-service-db
    networks:
      - peerprep-network

  user-service-db:
    container_name: user-service-db
    image: mongo:latest
    # volumes in the future...
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pgrep mongod"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: mongod --quiet --logpath /dev/null
    networks:
      - peerprep-network

networks:
  peerprep-network:
    driver: bridge
